### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by wisnoskij** [HatScripts/youtube-auto-liker#10]
Unless my installation just corrupted randomly, this script just stopped working with whatever update YT pushed.

Chrome-Tampermonkey

**Comment by HatScripts** [comment]
Hi @wisnoskij,
Is this a duplicate of #9 (the like button isn't turning blue unless you refresh the page)?
Are you using the latest version of the script (v1.3.3)?
If you change the `@version` to `DEV_VERSION`, what gets logged to the console (Ctrl+Shift+K)?

**Comment by wisnoskij** [comment]
Somehow I missed the update. sorry.
