### ISSUE TITLE
Don't work. Maybe new YouTube version?

### ISSUE THREAD

**Issue by kas-cor** [HatScripts/youtube-auto-liker#16]

**Comment by Kadah** [comment]
New Youtube UI is getting pushed out, just got it myself today. Looks like YT is bring the action menu UI over from the mobile app.

**Comment by HatScripts** [comment]
Thanks @kas-cor and @Kadah, this should be fixed now with https://github.com/HatScripts/youtube-auto-liker/commit/2ede4328190c7ce80b6c3a190c832a352e3a4b45 🚀
