### ISSUE TITLE
Auto-likes video even after I dislike

### ISSUE THREAD

**Issue by uiojaafdosijfafdssf** [HatScripts/youtube-auto-liker#19]
Just made a pull request! #20

Whenever I dislike a video before the progress bar percentage for the "Watch Threshold" setting is reached, it likes the video it has been reached.
You can reproduce this by setting the watch threshold to something above 0, disliking the video, then going past the progress percentage you entered.
I don't know how to fix this because I don't know any JavaScript or HTML. But I do know why it's happening, it's because you don't have the dislike button in the "SELECTORS" constant thing. If you didn't add this for a reason, go ahead and close this issue.

**Comment by HatScripts** [comment]
Thanks for making this issue and the related PR #20. Merged! 🚀
