### ISSUE TITLE
Script cannot use the player API from YouTube

### ISSUE THREAD

**Issue by PurpleMagick** [HatScripts/youtube-auto-liker#3]
The script didn't work for me, so I tried debugging it. Turns out it was the  `watchThresholdReached ()` function that was failing and in particular because of the calls `player.getCurrentTime()` and `player.getDuration()` - both of these properties turned out to be `undefined`, so the script fails because it tries to execute `undefined` as a function.

I'm not sure what the problem is, though. According to [this SO answer](https://stackoverflow.com/questions/14220250/how-to-call-this-youtube-function-from-greasemonkey) the function shouldn't be available. However, that's from 2013 and maybe things changed. I've only started using the script about a week ago and then only now noticed it didn't work. So, not sure if it has worked before or not.

My solution was a bit of a hack - I surrounded the check in a try/catch:
```
function watchThresholdReached() {
  let player = document.querySelector(SELECTORS.PLAYER)
  try {
    if (player) {
      return player.getCurrentTime() / player.getDuration() >= OPTIONS.WATCH_THRESHOLD
    }
  } catch (e) {}

  return true
}
```

It now works because it just defaults to `true` if there is an error just like it defaults to `true` if it doesn't find the player. However, I'm not sure this is really a good solution.

I'm using GreaseMonkey in Firefox 73.0.1 (64-bit) on Windows 10 to run the userscript, so I don't know if GM itself has more restrictions than alternatives or something else in my setup. It's possible that YouTube did something somewhat recently to make the player API not available again.

**Comment by PurpleMagick** [comment]
Small update, decided to try the script running in Tampermonkey in Firefox and it works as is. That means that the problem is with Greasemonkey. I'm really not sure why one can access the functionality and the other cannot, though. It might be the way they inject the script in the page.

**Comment by HatScripts** [comment]
I'm sorry for the huge delay in getting back to you. I've not used Greasemonkey before, and have never had a problem accessing the player API with Tampermonkey, so that's quite strange. Are you able to confirm whether this is still an issue with the latest version of GM?

Perhaps I should stop getting the video's time elapsed/total duration like that. I was already planning to update the script to use MutationObservers so with that I could just have it watch these elements that display the time info:

<img width="314" alt="screenshot" src="https://user-images.githubusercontent.com/5691865/91647354-41a02200-ea9d-11ea-8559-ef4e8a0d248c.png">

**Comment by PurpleMagick** [comment]
> Are you able to confirm whether this is still an issue with the latest version of GM?

Yes, it is. However, since reporting this, I've found out that quite a lot of scripts don't work with GM because that script manager is quite strict with what it allows userscripts to use. Many authors just choose to ignore supporting GM and it's something I also endorse. I've switched over to using ViolentMonkey as a script manager instead.

I'd be happy if you closed this as "won't fix". Unless you really want to try and go around the restrictions. I personally think it won't be worth it but you can choose yourself. It might be interesting to learn how to support more limited scripts.

And thanks for getting back to me. I had actually forgotten I reported this otherwise I would have updated with the above earlier.
