### ISSUE TITLE
Not working again

### ISSUE THREAD

**Issue by kevdinsation** [HatScripts/youtube-auto-liker#30]
Not sure why but it is not working for me both in edge and chrome even with version 1.3.26

No videos are being liked

**Comment by n3rdyguy** [comment]
Same here, using Chrome version 119.0.6045.59 + Tampermonkey
<img width="535" alt="err" src="https://github.com/HatScripts/youtube-auto-liker/assets/693296/91dbe889-7651-42dd-b85d-708842e21dd5">

**Comment by kevdinsation** [comment]
Here are my settings in edge. 

![image](https://github.com/HatScripts/youtube-auto-liker/assets/89745267/8e7fe14c-e36b-4971-8224-bb1e16216291)

In chrome I installed everything fresh and didn't log into YouTube, but I changed the settings to match edge and like videos to channels I am not subscribed to.

Here is the HTML from edge

[div id=below class=style-scope ytd-.txt](https://github.com/HatScripts/youtube-auto-liker/files/13216675/div.id.below.class.style-scope.ytd-.txt)

**Comment by kevdinsation** [comment]
Unfortunately, the issue is not resolved with your update. Videos are still going unliked both in edge and chrome. I have now tried with both tampermonkey and violentmonkey. I get the notification that a script is running on the page, but the button stays unliked.

**Comment by kevdinsation** [comment]
Its working again! thank you!

**Comment by SiTWulf** [comment]
Again not working.

YouTube Auto-Liker:  Checking whether subscribed...
userscript.html?name=YouTube-Auto-Liker.user.js&id=9f03644a-764f-4afa-93ac-061af1af23df:1067 YouTube Auto-Liker:  We are subscribed
userscript.html?name=YouTube-Auto-Liker.user.js&id=9f03644a-764f-4afa-93ac-061af1af23df:1092 YouTube Auto-Liker:  Trying to like video...
userscript.html?name=YouTube-Auto-Liker.user.js&id=9f03644a-764f-4afa-93ac-061af1af23df:1081 YouTube Auto-Liker:  Failed to like video: Error: Couldn't find like button. Will try again in 5000 ms...

**Comment by CelsiusVi** [comment]
Script is not working again for some users.
Here's a txt with the information you requested previously in the thread to see if it can help. I'm using the latest .26 version of the script.
Thanks for doing this, highly appreciated.
[below-style-scope.txt](https://github.com/HatScripts/youtube-auto-liker/files/13520346/below-style-scope.txt)

**Comment by CelsiusVi** [comment]
Indeed, .28 worked like a charm. Thanks again for the hard work.
