### ISSUE TITLE
Doesn't work anymore :(

### ISSUE THREAD

**Issue by riccardosimo** [HatScripts/youtube-auto-liker#34]
Hi guys :)
Since 3/4 days the script stopped working :( My chrome version is 121.0.6167.57. Do u have the same problem or it's just me?

**Comment by bonelifer** [comment]
@riccardosimo Hadn't been working for me. I use this one now: https://greasyfork.org/en/scripts/482555-youtube-auto-like

**Comment by HatScripts** [comment]
Should be working again now, (v1.3.28, https://github.com/HatScripts/youtube-auto-liker/commit/8aaab952aeacd2d950ed24a55103839f8f2ab156)
