### ISSUE TITLE
Browser DOM Security Update Causing Malfunction

### ISSUE THREAD

**Issue by topfishowo** [HatScripts/youtube-auto-liker#36]
I've been experiencing some issues with the YouTube Auto-Liker extension you developed. It seems that a recent browser security update is affecting the normal operation of the plugin.
![image](https://github.com/user-attachments/assets/2f41f910-af19-405d-94c9-bf6d0807d8cd)

https://web.dev/articles/trusted-types#fix-the-violations

**Comment by HatScripts** [comment]
I don't recognize the code in your screenshot. Where did you get it from?

**Comment by topfishowo** [comment]
I found an error in the component console after pressing Settings.
![image](https://github.com/user-attachments/assets/2ed8f20f-e137-409f-a165-7547bd230d6b)

**Comment by topfishowo** [comment]
from // @require        https://raw.githubusercontent.com/sizzlemctwizzle/GM_config/master/gm_config.js

**Comment by DrymarchonShaun** [comment]
As far as I can tell, I managed to get this working (with copilot's help, I don't know anything about js) at https://github.com/DrymarchonShaun/youtube-auto-liker/tree/master by removing the settings menu entirely and storing the settings as userscript values directly.

(The `remove-gm_config` branch only includes the changes, in `master` I also changed the update urls to my forked repo)
