### ISSUE TITLE
Script can't detect being subscribed anymore.

### ISSUE THREAD

**Issue by Eisys** [HatScripts/youtube-auto-liker#5]
This started today.

If I set "LIKE_IF_NOT_SUBSCRIBED" to true, then it works and likes the video. When it's false, as I normally use it, it doesn't like videos from channels I'm subbed to anymore.

Windows 10 latest
Chrome Beta Version 90.0.4430.61 (Official Build) beta (64-bit)
Tampermonkey 4.12

**Comment by Gigafrost** [comment]
I have the same issue.
Subbed channels no longer work.

**Comment by Gigafrost** [comment]
I have the same issue.
Subbed channels no longer work. Looks like YouTube updated their API and broke this script.

**Comment by diggtrap** [comment]
Can confirm it stopped working as OP stated.

Replicated the "LIKE_IF_NOT_SUBSCRIBED" change and it worked. Either google or youtube changed something impeding that to work.

**Comment by Gigafrost** [comment]
I have the same issue.
Subbed channels no longer work.

**Comment by Eisys** [comment]
I have found a fix until HatScripts fixes it himself.

Line 54 in the script, Change "paper-button" to "tp-yt-paper-button" w/o quot. marks.

Like this:
[Before](https://i.imgur.com/6c6ZUYc.png)

[After](https://i.imgur.com/BrHe5ZC.png)

**Comment by Gigafrost** [comment]
> I have found a fix until HatScripts fixes it himself.
> 
> Line 54 in the script, change "paper-button" to "tp-yt-paper-button" w/o quot. marks.
> 
> Like this:
> [Before](https://i.imgur.com/6c6ZUYc.png)
> 
> [After](https://i.imgur.com/BrHe5ZC.png)
> 
> Credit for the fix goes to "good-praxis" on Greasyfork.

Can confirm that this workaround fixes the issue (at the time of writing). Not sure if it will continue to work, but Eisys' solution fixed my issue PERFECTLY!

**Comment by sonst-was** [comment]
Someone already created a pull request (what I just wanted to do) for exactly this: https://github.com/HatScripts/youtube-auto-liker/pull/4

Hasn't been accepted yet sadl...

**Comment by HatScripts** [comment]
Thank you all, merged #4.

**Comment by Antony256** [comment]
Hi, I didn't get this fix with tampermonkey, I assume because the version number hasn't been updated.

**Comment by Eisys** [comment]
One can go to the Greasemonkey page and hit reinstall version 1.3.1. It does change the line.

**Comment by HatScripts** [comment]
@Antony256 Thanks, fixed with https://github.com/HatScripts/youtube-auto-liker/commit/37717a9ba29488aa4286d1cef8cad005cb12e7ee.
