### ISSUE TITLE
Stopped working again

### ISSUE THREAD

**Issue by diggtrap** [HatScripts/youtube-auto-liker#7]
Since yesterday (May 21st, 2021), the script doesn't auto like, but the bar under the thumbs up lights up as if it was liked.

![image](https://user-images.githubusercontent.com/38831894/119243954-e7228680-bb41-11eb-8f74-e61e4f1bb4fc.png)

**Comment by sonst-was** [comment]
Same here, the script seems to think that the like button was indeed clicked:
`YouTube Auto-Liker:  Checking whether subscribed... YouTube Auto-Liker.user.js:84:11
YouTube Auto-Liker:  We are subscribed YouTube Auto-Liker.user.js:90:11
YouTube Auto-Liker:  Trying to like video... YouTube Auto-Liker.user.js:123:11
YouTube Auto-Liker:  Found like button YouTube Auto-Liker.user.js:136:13
YouTube Auto-Liker:  It's unclicked. Clicking it... YouTube Auto-Liker.user.js:140:13
YouTube Auto-Liker:  Successfully liked video YouTube Auto-Liker.user.js:143:13
YouTube Auto-Liker:  Checking whether subscribed... YouTube Auto-Liker.user.js:84:11
YouTube Auto-Liker:  We are subscribed YouTube Auto-Liker.user.js:90:11
YouTube Auto-Liker:  Trying to like video... YouTube Auto-Liker.user.js:123:11
YouTube Auto-Liker:  Like button has already been clicked`

**Comment by diggtrap** [comment]
> Edit: It might still like the videos despite youtube showing it weirdly as in OPs pic - atleast I still get the "Added to liked videos" notification which is from youtube itself afaik.

Just checked and you're indeed correct. Seems to be a visual bug only then.

**Comment by aleczk** [comment]
Same thing here. The video is being liked, if you refresh the page the button will show as blue, but it's not working as before, where the button would turn blue. Only the little bar below it turns blue automatically when it's liked.

![image](https://user-images.githubusercontent.com/16522249/119398391-ddb62d00-bcad-11eb-9c51-2d3ffa263c22.png)

**Comment by HatScripts** [comment]
Thanks for reporting. Fixed with https://github.com/HatScripts/youtube-auto-liker/commit/8d9266743504a37db17c04e50cbff99bbcff50d7.
