### ISSUE TITLE
Like button is still not turning blue without refreshing

### ISSUE THREAD

**Issue by NoahBK** [HatScripts/youtube-auto-liker#9]
This bug was fixed before hand, but I guess it's broken again. The like button isn't turning blue anymore without a refresh of the page. The script is working just fine, it's just a visual bug I'm assuming.

[Link to previous post](https://github.com/HatScripts/youtube-auto-liker/issues/7)

**Comment by HatScripts** [comment]
Hi @NoahBK, I'm not able to replicate this bug. Are you using the latest version of the script (v1.3.3)?

If you open the DOM inspector (Ctrl+Shift+C) while on a video page, and search (Ctrl+F) for `ytd-video-primary-info-renderer #top-level-buttons-computed > ytd-toggle-button-renderer:nth-child(1)`, do you get a single result (1 of 1)? Is the found element visible on screen?

**Comment by NoahBK** [comment]
I am using the latest version (v1.3.3) and I do only get 1 result when searching for what  you're looking for. Like I said earlier, the script does in fact work. It just doesn't work when watching the video, visually. I have to reload the page. When I do, the like button is always blue like expected. If there is anything I can share to make it easier for you to fix I will be happy to help.

**Comment by NoahBK** [comment]
I know that it doesn't help, but seemingly randomly the script is now working again. Nothing has changed on my end. But, the visual bug is not happening anymore.
